run_name: all_acc_t1_cross_valid_5
description: "This training routine uses the T1map data with all acceleration factors with 5-fold cross validation."

recon_backbone_config:
  forward_operator: fft2
  backward_operator: ifft2
  in_channels: 18
  num_steps: 6
  recurrent_hidden_channels: 96
  recurrent_num_layers: 4
  no_parameter_sharing: True
  learned_initializer: True
  initializer_initialization: sense
  initializer_channels: [32, 32, 64, 64]
  initializer_dilations: [1, 1, 2, 4]
  initializer_multiscale: 3
  normalized: false


sensitivity_refinement_config:
  in_channels: 18
  out_channels: 18
  num_filters: 8
  num_pool_layers: 4
  dropout_probability: 0.0


dataset_config:
  acceleration_factors: [4., 8., 10.]
  modality: t1map
  overwrite_split: = false


trainer_config:
  batch_size: 2
  dataloader_num_workers: 8
  weight_decay: 0.
  lr_decay: 0.9
  lr_init: 0.001
  max_epochs: 200
  save_checkpoint_every: 1
  save_optimizer_factor: 2
  validation_every: 10
  load_pretrained_weight: null
  load_pretrained_latest: false
  combined_loss_weight:
    nmse: 1.0
    ssim: 1.0


training_tracking_config:
  save_training_loss_every: 10
  save_training_image_every: 500
